require("spectre").setup()
require("refactoring").setup()
require("leap").set_default_keymaps()
require("diffview").setup()
require("neogit").setup()
require("nvim-surround").setup()
require("which-key").setup()
require("colorizer").setup({ user_default_options = { names = false } })
require("dressing").setup()
